library(tidyverse)

source('R/plot-variables.R')

export_dir <- '/home/labs/dnalab/share/lims/R/gcat-cohort/output/export'
gcat <- read_csv(file.path(export_dir, 'QUESTIONARI/data.csv'))
participants <- read_csv(file.path(export_dir, 'Participants/data.csv'))

#source('R/check/check-last-intake.R')
source('R/check/check-locations.R')
source('R/check/check-locations-residencia.R')

source('R/check/check-height.R')
source('R/check/check-weight.R')
source('R/check/check-bmi.R')
source('R/check/check-whr.R')
source('R/check/check-hr.R')
source('R/check/check-participants.R')
source('R/check/check-follow-up.R')
source('R/check/check-age.R')
source('R/check/check-gender.R')
source('R/check/check-birth-weight.R')
source('R/check/check-self-perceived-health.R')
source('R/check/check-hair.R')
source('R/check/check-skin.R')
source('R/check/check-eyes.R')
source('R/check/check-women-health.R')
source('R/check/check-offspring.R')
source('R/check/check-sleep.R')
source('R/check/check-smoking.R')
source('R/check/check-predimed.R')
source('R/check/check-work.R')
source('R/check/check-psychology.R')
source('R/check/check-eating.R')
source('R/check/check-conditions.R')
source('R/check/check-medications.R')
source('R/check/check-core.R')
source('R/check/check-alcohol.R')

source('R/heritability.R')
