library(tidyverse)

#source('R/check-last-intake.R')
source('R/check-locations.R')
source('R/check-locations-residencia.R')

export_dir <- '/home/labs/dnalab/share/lims/R/gcat-cohort/output/export'
gcat <- read_csv(file.path(export_dir, 'QUESTIONARI/data.csv'))
participants <- read_csv(file.path(export_dir, 'Participants/data.csv'))

source('R/check-height.R')
source('R/check-weight.R')
source('R/check-bmi.R')
source('R/check-whr.R')
source('R/check-hr.R')
source('R/check-participants.R')
source('R/check-follow-up.R')
source('R/check-age.R')
source('R/check-gender.R')
source('R/check-birth-weight.R')
source('R/check-self-perceived-health.R')
source('R/check-hair.R')
source('R/check-skin.R')
source('R/check-eyes.R')
source('R/check-women-health')
source('R/check-offspring.R')
source('R/check-sleep.R')
source('R/check-work.R')
source('R/check-psychology.R')
source('R/check-eating.R')
source('R/check-conditions.R')
source('R/check-medications.R')
source('R/check-core.R')

source('R/heritability.R')
